---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    app: JGroupsWildflyPoC
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: net.fhirfactory.pegacorn
  name: privnet-poc
spec:
  ports:
    - name: https
      port: 10000
      protocol: TCP
      targetPort: 8443
    - name: jgroups
      port: 20000
      protocol: TCP
      targetPort: 7900
  selector:
    app: JGroupsWildflyPoC
    provider: fabric8
    group: net.fhirfactory.pegacorn
  type: "LoadBalancer"
  loadBalancerIP: 10.88.88.100