---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project={{ .Values.subsystemInstant.subsystemName }}&var-version={{ .Values.subsystemImageProperties.imageVersion }}
  labels:
    app: {{ .Values.subsystemInstant.subsystemName }}
    version: "{{ .Values.subsystemInstant.subsystemVersion }}"
    group: {{ .Values.subsystemInstant.solutionGroup }}
  name: {{ .Values.subsystemInstant.subsystemName }}
spec:
  replicas: {{ .Values.deploymentMode.processingPlantReplicationCount | default 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.subsystemInstant.subsystemName }}
      group: {{ .Values.subsystemInstant.solutionGroup }}
  template:
    metadata:
      annotations:
        fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project={{ .Values.subsystemInstant.subsystemName }}&var-version={{ .Values.subsystemImageProperties.imageVersion }}
      labels:
        app: {{ .Values.subsystemInstant.subsystemName }}
        version: {{ .Values.subsystemInstant.subsystemVersion }}
        group: {{ .Values.subsystemInstant.solutionGroup }}
        cluster: {{ .Values.deploymentZone.securityZoneName }}
        date: "{{ date "20060102-150405" .Release.Time }}"
    spec:
      serviceAccountName: jgroups-kubeping-service-account
      {{- if (.Values.acrSecretName) }} 
      imagePullSecrets:
        - name: {{ .Values.acrSecretName }}
      {{- end }}
#      affinity:
#        nodeAffinity:
#          preferredDuringSchedulingIgnoredDuringExecution:
#          - weight: 1
#            preference:
#              matchExpressions:
#              - key: computeResources
#                operator: In
#                values:
#                - High
      containers:
        - env:
          - name: KUBERNETES_SERVICE_NAME
            value: {{ .Values.subsystemInstant.subsystemName }}
          - name: HELM_RELEASE_TIME
            value: "{{ date "20060102-150405" .Release.Time }}"
          - name: MY_HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_CLUSTER_NAME
            value: {{ .Values.deploymentZone.securityZoneName }}
          - name: MY_PROCESSING_PLANT_NAME
            value: {{ .Values.subsystemInstant.subsystemName }}
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DEPLOYMENT_CONFIG_FILE
            value: {{ .Values.deploymentMode.deploymentConfig }}
          # Set the minimum memory that will be available on the node to assign to the container to be the jvmMaxHeapSizeMB plus 128 MB
          # for the native heap and operation system processes associated with running Java
          # See https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/#motivation-for-memory-requests-and-limits
          # and https://www.alibabacloud.com/blog/kubernetes-demystified-restrictions-on-java-application-resources_594108
          resources:
            requests:
              memory: "128Mi"
          image: {{ .Values.subsystemImageProperties.repository }}{{ .Values.subsystemImageProperties.imageName }}:{{ .Values.subsystemImageProperties.imageVersion }}
          imagePullPolicy: {{ .Values.subsystemImageProperties.pullPolicy }}
          name: {{ .Values.subsystemInstant.subsystemName }}
          ports:
            - containerPort: 12345
              name: admin
              protocol: TCP
          securityContext:
            privileged: false
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}